# Generated by Django 4.2.5 on 2023-09-21 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voiceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='audiorecord',
            table='mytable',
        ),
    ]
